Adding info on smart contracts
w3f/polkadot-wiki-old pull request #143
Opened 2019-05-02 12:21 UTC by lsaether

2019-05-02 13:09 UTC, lsaether commented
Should be good for now -- I want to find /write more examples but we should probably post this page in case anyones looking on the wiki for these links.

2019-05-02 13:39 UTC, laboon requested changes
Made some rewording changes and added more detail on smart contracts.  I used suggestions this time, thanks!

There's definitely more room to add things on smart contracts but I think this is fine for a first shot.

2019-05-02 13:39 UTC, laboon commented on docs/polkadot/build/smart-contracts.md
> +The Polkadot relay chain will not support smart contracts natively, however parachains on Polkadot will support smart contracts. There are already announced projects such as [Edgeware](https://edgewa
```suggestion
The Polkadot relay chain will not support smart contracts natively.  However, parachains on Polkadot will support smart contracts. There are already announced projects such as [Edgeware](https://edgewa.re), and thanks to the Substrate built-in [contract module](https://crates.parity.io/srml_contract/index.html), it is likely that more parachains will support this feature.
```

2019-05-02 13:39 UTC, laboon commented on docs/polkadot/build/smart-contracts.md
> +When you build a smart contract it will be eventually be deployed to a target chain with its own environment. While parachains allow the developer to declare the environment of their chain, even allo
```suggestion
When you build a smart contract, it will be eventually be deployed to a target chain with its own environment. Parachains allow the developer to declare the environment of their own chain, even allowing others to write smart contracts for it.
```

2019-05-02 13:39 UTC, laboon commented on docs/polkadot/build/smart-contracts.md
> +Smart contracts must implement a form of gas metering or else make full nodes vulnerable to DOS attacks. Things like infinite loops could possibly consume the computation of a chain entirely and bloc
```suggestion
Smart contracts must find a way to limit their own execution, or else full nodes are vulnerable to DOS attacks. An infinite loop in a smart contract, for example, could consume the computational resources of an entire chain, preventing others from using it. The [halting problem](https://en.wikipedia.org/wiki/Halting_problem) shows that with a powerful enough language, it is impossible to know ahead of time whether or not a program will ever cease execution.  Some platforms, such as Bitcoin, get around this constraint by providing a very restricted scripting language.  Others, such as Ethereum, "charge" the smart contract "gas" for the rights to execute their code.  If a smart contract does get into a state where execution will never halt, it eventually runs out of gas, ceases execution, and any state transition that would have been made by the smart contract is rolled back.  
```

2019-05-02 13:39 UTC, laboon commented on docs/polkadot/build/smart-contracts.md
> +Smart contracts must implement a form of gas metering or else make full nodes vulnerable to DOS attacks. Things like infinite loops could possibly consume the computation of a chain entirely and bloc
There really are two ways around this problem - gas (exemplified by Ethereum) and using a non-Turing-complete language / whitelisting scripts like Bitcoin.  Maybe there are even more that I'm not familiar with, but those are the two main ones in the blockchain space AFAIK.  I also wanted to expand out what exactly "gas" is.

2019-05-02 13:39 UTC, laboon commented on docs/polkadot/build/smart-contracts.md
> +Parachains get around this constraint and contain no notion of gas for their own native logic. This means that some things become more viable and easier to implement for the developer, but it also me
```suggestion
Parachains can implement arbitrarily powerful programming languages and also contain no notion of gas for their own native logic. This means that some functionality is easier to implement for the developer, but it also means there are some constructs, such as a loop without a terminating condition, which should _never_ be implemented.  Leaving certain logic, such as complex loops which could possibly run indefinitely, to a non-smart contract layer, or even trying to eliminate it entirely, will often be a wiser choice.
```

2019-05-02 14:35 UTC, lsaether commented on docs/polkadot/build/smart-contracts.md
> +Smart contracts must implement a form of gas metering or else make full nodes vulnerable to DOS attacks. Things like infinite loops could possibly consume the computation of a chain entirely and bloc
nice, thanks!

2019-05-02 14:36 UTC, lsaether commented
Suggestions accepted

2019-05-03 07:34 UTC, laboon approved these changes

2019-05-03 07:34 UTC, laboon commented
:lgtm:

2019-05-03 07:35 UTC, merged

2019-05-03 07:35 UTC, laboon commented
@lsaether - Sorry, I accidentally merged this. after approving changes..