Misc updates
w3f/polkadot-wiki-old pull request #146
Opened 2019-05-03 09:42 UTC by lsaether

This PR will just contain some misc updates I find while working on examples of smart contracts.

2019-05-03 21:40 UTC, lsaether commented
Will look into more on Consensus soon, but for now I think this covers the immediate corrections that were reported.

2019-05-06 17:00 UTC, laboon reviewed
Overall good, a few comments on eventual consistency

2019-05-06 17:00 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +## What is PoW and PoS?
```suggestion
## What are PoW and PoS?
```

2019-05-06 17:00 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +Proof of Work (PoW) and Proof of Stake (PoS) have been used as short hand to refer to consensus mechanisms of blockchains, but it does not capture the full picture. PoW is the method for agreeing on
```suggestion
Proof of Work (PoW) and Proof of Stake (PoS) have been used as short hand to refer to consensus mechanisms of blockchains, but that does not capture the full picture. PoW is the method for agreeing on a block author and part of the fuller [Nakamoto consensus](#nakamoto-consensus) that also encompasses a chain selection algorithm (longest chain rule in Bitcoin). Similarly, PoS is a set of rules for selecting the validator set and does not specify a chain selection rule or how a chain might reach finality. PoS algorithms have traditionally been paired with an algorithm for coming to Byzantine agreement between nodes. For example, [Tendermint](./comparisons/cosmos.md) is a practical Byzantine fault tolerant algorithm which uses PoS as its validator set selection method.
```

2019-05-06 17:00 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
```suggestion
Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probable finality, also sometimes termed "eventual consensus", is that under some assumptions about the network and participants, if we see a few blocks building on a given block, we can estimate the probability that it is final. However, finality gadgets such as GRANDPA or Ethereum's Casper FFG are designed to give stronger guarantees on the finality of blocks, that they can never be reverted after some process of byzantine agreements has taken place. The notion of irreversible consensus is known as _provable finality._
```

2019-05-06 17:00 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
Probable finality is not exactly the same as eventual consensus.  There are variations on Nakamoto consensus that use PoW but which still allow stronger guarantees of finality, such as checkpointing - see the early Bitcoin source code ( https://github.com/bitcoin/bitcoin/blob/f5a623eb66c81d9d7b11206d574430af0127546d/src/chainparams.cpp#L146 )  or Bitcoin Cash ABC's more recent checkpoint right before the SV fork ( https://github.com/Bitcoin-ABC/bitcoin-abc/commit/651ac4461c2c92952df39f75a9d177c746e60b57 ).  Not trying to wade into the minefield of whether or not these are good ideas, merely that you _can_ have a proof-of-work chain that has a stronger consensus guarantee.

2019-05-06 17:00 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
```suggestion
A pure Nakamoto consensus blockchain which runs PoW is only able to achieve the notion of _probable finality_ and reach _eventual consensus_. Probable finality means that under some assumptions about the network and participants, if we see a few blocks building on a given block, we can estimate the probability that it is final.  Eventual consensus means that at some point in the future, all nodes will agree on the truthfulness of one set of data.  This eventual consensus may take a long time and will not be able to be determined how long it will take ahead of time.  However, finality gadgets such as GRANDPA or Ethereum's Casper FFG are designed to give stronger and quicker guarantees on the finality of blocks - specifically, that they can never be reverted after some process of byzantine agreements has taken place. The notion of irreversible consensus is known as _provable finality._
```

2019-05-06 17:00 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +There are two acronyms we use when we talk about the consensus protocol of Polkadot, GRANDPA and BABE. We talk about both of these acronyms because Polkadot uses what is known as **hybrid consensus**
```suggestion
There are two acronyms we use when we talk about the consensus protocol of Polkadot, GRANDPA and BABE. We talk about both of these acronyms because Polkadot uses what is known as **hybrid consensus**. Hybrid consensus splits up the finality gadget from the block production mechanism. This allows for blocks to be produced more rapidly and the slower finality mechanism to run in a separate process to finalize blocks without risking slower transaction processing. 
```

Don't we want to not risk _slower_ instead of _quicker_ transaction processing?

2019-05-06 17:01 UTC, laboon requested changes
Couple of changes requested

2019-05-06 17:33 UTC, lsaether commented
All suggestions accepted. Interesting point regarding checkpoints in bitcoin.

2019-05-06 18:01 UTC, laboon approved these changes
👍

2019-05-06 18:04 UTC, merged

2019-05-06 20:47 UTC, rphmeier commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
I'm not sure I would lump checkpointing in with the automated decentralized consensus. One requires human intervention (and trust in a specific person or group) and the other is rooted in economic incentives.

2019-05-07 00:01 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
Perhaps checkpointing isn't the most relevant example for this. Casper or other hybrid PoW/PoS schemes can have a PoW chain that can have a finality that isn't just plain ol' Nakamoto consensus, though, so I think it makes more sense to not say that "PoW blockchains can _only_ reach probable consensus."

But I'm open if there's a better way to describe that or if my understanding is incorrect.

2019-05-07 09:09 UTC, rphmeier commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
Right, I agree that finality gadgets are the right example for that.

2019-05-07 09:47 UTC, laboon commented on docs/polkadot/learn/consensus.md
> +Nakamoto consensus blockchains which run PoW are only able to achieve the notion of _probable finality_. Probably finality, also sometimes termed "eventual consensus", is that under some assumptions
👍 Thanks!