Adds gov content
w3f/polkadot-wiki-old pull request #162
Opened 2019-05-08 11:40 UTC by lsaether

fixes #151 fixes #155 

starts #12 and #158 

- Fixes rendering of Latex in markdown
- Adds diagrams to governance page
- Adds decision graphs 
- Starts council overview
- Removes duplicated content

2019-05-09 13:28 UTC, laboon requested changes
Overall good, a few minor comments/concerns

2019-05-09 13:28 UTC, laboon commented on docs/polkadot/node/governance/index.md
> +### [How to create a proposal]()
These links appear to be missing.  If they don't exist, perhaps it's better to just make a comment and add them in later?

2019-05-09 13:28 UTC, laboon commented on docs/polkadot/node/governance/index.md
> +### How are council motions made? What can they do?
There's no content in this section...

2019-05-09 13:28 UTC, laboon commented on docs/polkadot/node/governance/index.md
> +Voters must also submit a bond to signal approvals for council seats. If a voter becomes inactive, they may be "reaped" by an external actor and their bond claimed as a reward. The process of the run
It seems like this is missing some content, as it starts with "Voters must also..."

Or should it just start with "Voters must submit a bond.."?

2019-05-09 13:28 UTC, laboon commented on docs/polkadot/learn/governance.md
> +```
Just a comment, no action required:

ASCII drawings are OK for now I think, especially for simple things, but do you think that we should add actual images in the future?

2019-05-09 14:05 UTC, lsaether commented on docs/polkadot/learn/governance.md
> +```
ASCII drawings are good enough to show a point and come out better than what I would be able to do in GIMP. Totally real images would be better but it depends on the level of priority and the capacity of the people with those skills.

2019-05-09 14:08 UTC, laboon commented on docs/polkadot/learn/governance.md
> +```
Yeah I think it's low priority for now, just thinking ahead

2019-05-09 14:09 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +### [How to create a proposal]()
yes they are TODO

2019-05-09 14:20 UTC, ansonla3 commented
@laboon I will pick up #12  & #158   :)

2019-05-09 14:38 UTC, ansonla3 approved these changes

2019-05-10 11:03 UTC, lsaether commented
PR will follow from @ansonla3 completing the governance content.

2019-05-13 10:49 UTC, merged