add governance content (council) & election process
w3f/polkadot-wiki-old pull request #169
Opened 2019-05-13 10:11 UTC by ansonla3

2019-05-13 12:26 UTC, lsaether requested changes

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +In order to make any changes to the network, the idea is to compose of active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is propos
```suggestion
In order to make any changes to the network, the idea is to compose of active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is proposed by the public (DOTs holders) or council, it finally will have to go through the [referenda](#referenda) to let all DOTs holders make the decision.
```

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +In order to make any changes to the network, the idea is to compose of active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is propos
```suggestion
In order to make any changes to the network, the idea is to compose of active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is proposed by the public(DOT holders) or council, it finally will have to go through the [referenda](#referenda) to let all DOT holders make the decision.
```

Should it be DOTs holders or DOT holders? I think DOT holders sounds more right, since we would say "share holders" if referring to common stock of a company.

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +- [Proposing proposals](#proposing-proposals) (Involved info: [Referenda](#referenda))
```suggestion
- [Proposing referenda](#proposing-proposals) (Involved info: [Referenda](#referenda))
```

I think referenda would be preferred since "proposing proposals" uses the same root word in two words.

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +- [Voting in a referendum](#voting-in-a-referendum) (Involved info: [Voluntary Locking](#voluntary-locking)
optionally could say "Voting for a proposal" to not repeat referenda from above.

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +- [Vote Counting](#vote-counting) (Involved info: [Adaptive Quorum Biasing](#adaptive-quorum-biasing))
tallying?

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +### Proposing proposals
```suggestion
### Proposing referendums
```

According to the [wikipedia](https://en.wikipedia.org/wiki/Referendum) article on referendum, the plural form of referendum is more commonly `referendums`, thoughts about switching over to this form throughout the governance section of the wiki? We can also check with Parity docs team to see if they've settled on the correct plural form.

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +- **Public**: Anyone can propose a proposal by depositing minimum value in a certain period (No. of Blocks). If someone likes the proposal, they could deposit the same amount of tokens to support it.
```suggestion
- **Public**: Anyone can propose a referendum by depositing minimum value in a certain period (No. of Blocks). If someone likes the proposal, they could deposit the same amount of tokens to support it. The one with the highest number of supported proposal will be selected to be a referendum. Those tokens will be released once the proposal is tabled. At genesis, every two weeks will have a referendum on the most supported proposal.
```

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +    Unanimous Council - Where everyone in the council thinks that is a good proposal, it can move to the referenda.
```suggestion
    Unanimous Council - When all members of the council agrees on a proposal, it can be moved to a referendum.
```

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +    Majority Council - Where simple-majority council agreement must have more aye votes to nay votes to be accepted.
```suggestion
    Majority Council - When agreement from only the simple majority of council members is needed. (More Aye votes to Nay votes for acceptance, more Nay votes to Aye votes for rejection.) 
```

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +To calculate the voting for a proposal, we need this four information.
```suggestion
We need the following information to calculate the required voting thresholds of proposals:
```

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
>  ```
Wouldn't this be better as a simple markdown list?

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +$${450 \over \sqrt{1050}} < {600 \over \sqrt{1000}}$$
Where do the numbers 1050 and 1000 come from?

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +if there is publicly submitted referenda only has 25% turnout, the tally of "aye" votes has to reach 66% for it to pass since we applied the ``Positive Turnout Bias``.
```suggestion
If there is publicly submitted referenda only has 25% turnout, the tally of "aye" votes has to reach 66% for it to pass since we applied the ``Positive Turnout Bias``.
```

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +                                Candidates
Wouldn't it be better to use a [markdown table](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables) for this?

2019-05-13 12:26 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +                                Candidates
Same as above regarding markdown table

2019-05-13 12:26 UTC, lsaether commented on mkdocs.yml
> +    - mdx_math
I think this extension will not be needed since we use JS from the research wiki to render LaTeX? https://github.com/w3f/polkadot-wiki/pull/162/files#diff-45ee620855dad847bea76b49932ad7db

2019-05-13 12:26 UTC, lsaether commented on requirements.txt
> +python-markdown-math==0.6
Same as above regarding JavaScript

2019-05-13 12:31 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +- [Proposing proposals](#proposing-proposals) (Involved info: [Referenda](#referenda))
agree

2019-05-13 12:31 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +In order to make any changes to the network, the idea is to compose of active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is propos
agree

2019-05-13 12:39 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +$${450 \over \sqrt{1050}} < {600 \over \sqrt{1000}}$$
1050 = the total number of votes for this proposal
1000 =  the number of tokens issued in this network

2019-05-13 12:43 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +- [Vote Counting](#vote-counting) (Involved info: [Adaptive Quorum Biasing](#adaptive-quorum-biasing))
yeah, it sounds better

2019-05-13 15:42 UTC, laboon commented on docs/polkadot/node/governance/index.md
> +### Proposing proposals
Looks like they are going with "referenda" according to this very recent commit from Joshy - 

https://github.com/paritytech/substrate/commit/7e7192c0f48e7ca97bc54327df55a72ccd2d479c

2019-05-13 16:16 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +### Proposing proposals
good catch! @ansonla3 did you see this comment?

2019-05-13 16:19 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +### Proposing proposals
@laboon oh. thanks! :)

2019-05-14 09:13 UTC, lsaether requested changes

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +- **Public**: Anyone can propose a referenda by depositing minimum value in a certain period (No. of Blocks). If someone likes the proposal, they could deposit the same amount of tokens to support it
```suggestion
- **Public**: Anyone can propose a referenda by depositing minimum value in a certain period (No. of Blocks). If someone likes the proposal, they could deposit the same amount of tokens to support it. The one with the highest number of supported proposal will be selected to be a referendum. Those tokens will be released once the proposal is tabled. At genesis, every two weeks will have a referendum on the most supported proposal.
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +    Unanimous Council - When all members of the council agrees on a proposal, it can be moved to a referenda.
```suggestion
    Unanimous Council - When all members of the council agrees on a proposal, it can be moved to a referendum.
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +To vote, a voter must lock their tokens up for at least the enactment delay period beyond the end of the referenda. This is in order to ensure that some minimal economic buy-in to the result is neede
```suggestion
To vote, a voter must lock their tokens up for at least the enactment delay period beyond the end of the referendum. This is in order to ensure that some minimal economic buy-in to the result is needed and to dissuade vote selling. At the same time, holding only a small amount of DOT tokens does not mean that they cannot influence the referendum result, you can read more about the [Voluntary Locking](#voluntary-locking).
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +$${against \over \sqrt{voters}} < {approve \over \sqrt{electorate}}$$
I think we should better define what this equation means and where it comes from before dropping it here. One or two sentences that explain what each of these parameters mean and where they come from. Similar to the code comment [here](https://github.com/paritytech/substrate/blob/master/srml/democracy/src/vote_threshold.rs#L73).  Also would be good to link to where in the code the equation comes from and what module as the source of the equation.

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +Based on the above result, proposal will be approved. In addition, only the winning voter's tokens are locked, which means if that referenda hurts the network, then those who voted against it can imm
```suggestion
Based on the above result, the proposal will be approved. In addition, only the winning voter's tokens are locked, which means if that referendum hurts the network, then those who voted against it can immediately get their locked tokens back. They can exit the network and sell their tokens to the market before the proposal becomes effective. Moreover, winning proposals are autonomously enacted only after some cool-down period.
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +$${13.887} < {15.492}$$
Looks good :+1:

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +Polkadot utilize an idea called `Voluntary Locking` that lets the token holders increasing their voting power by declaring how long they are willing to lock-up their DOTs, hence, the maximum number o
```suggestion
Polkadot utilizes an idea called `Voluntary Locking` that allows token holders to increase their voting power by declaring how long they are willing to lock-up their DOTs, hence, the maximum number of votes for each token holder will be calculated by the following formula:
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +Based on the current testnet setting, the maximum number of lock periods could NOT be more than 6.
```suggestion
Based on the current testnet setting, the maximum number of lock periods is set to 6.
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +For the top-N(say 4 in this example) runners-up, they can stay there and keep their votes persist until next election. After round 2, even though candidate A & B get the same votes in this round, can
```suggestion
For the top-N (say 4 in this example) runners-up, they can remain and their votes persist until the next election. After round 2, even though candidates A & B get the same number of votes in this round, candidate A gets elected because after adding the older unused approvals, it is higher than B.
```

2019-05-14 09:13 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +### [How to propose a referenda]()
Will this be different than `How to create a proposal`?

2019-05-14 09:23 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +### [How to propose a referenda]()
sounds remove ``How to create a proposal`` and use ``How to propose a referendum`` would be better

2019-05-14 13:53 UTC, ansonla3 commented on docs/polkadot/node/governance/index.md
> +$${against \over \sqrt{voters}} < {approve \over \sqrt{electorate}}$$
umum... I moved the description to the above & rephasing a bit to see would be better or not.

2019-05-15 08:50 UTC, lsaether requested changes
Just a few grammar fixes and then LGTM

2019-05-15 08:50 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +In order to make any changes to the network, the idea is to compose of active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is propos
```suggestion
In order to make any changes to the network, the idea is to compose active token holders and council together to administrate the network upgrade decision. No matter whether the proposal is proposed by the public (DOT holders) or council, it finally will have to go through the [referenda](../../learn/governance.md#referenda) to let all DOT holders make the decision.
```

2019-05-15 08:50 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +To better understand how council forms, please read [this section](#council).
```suggestion
To better understand how the council is formed, please read [this section](#council).
```

2019-05-15 08:50 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +- **Public**: Anyone can propose a referenda by depositing minimum value in a certain period (No. of Blocks). If someone likes the proposal, they could deposit the same amount of tokens to support it
```suggestion
- **Public**: Anyone can propose a referenda by depositing the minimum amount of DOTs for a certain period (No. of Blocks). If someone likes the proposal, they may deposit the same amount of tokens to support it. The proposal with the highest number of support bond will be selected to be a referendum. The bonded tokens will be released once the proposal is tabled. At genesis, every two weeks there will be a referendum for the most supported proposal.
```

2019-05-15 08:50 UTC, lsaether commented on docs/polkadot/node/governance/index.md
> +Depending on who are the entity proposed the proposal and whether all council members voted yes, there are three different scenarios. We can use following table for reference.
```suggestion
Depending on which entity proposed the proposal and whether all council members voted yes, there are three different scenarios. We can use following table for reference.
```

2019-05-15 08:57 UTC, lsaether approved these changes

2019-05-15 08:58 UTC, merged