Updating comparisons pages
w3f/polkadot-wiki-old pull request #180
Opened 2019-05-15 23:24 UTC by lsaether

- Cosmos 
  - [X] 1/2
  - [ ] 2/2
- [ ] Tezos
- [ ] Eth1.x
- [ ] Eth2.0

2019-05-16 10:15 UTC, cwgoes commented
Want to chat about Cosmos/Polkadot differences & similarities?

The best overview on the current state of IBC is [here](https://github.com/cosmos/ics/blob/master/ibc/1_IBC_ARCHITECTURE.md).

2019-05-16 10:37 UTC, lsaether commented
@cwgoes Sounds like a great idea, are you on Riot?

Would love to work on a mutually vetted page from both of us, I think it would end up being the most fair to both projects. It's hard for a single person to keep track of both what Polkadot is doing and Cosmos is doing at the same time :)

2019-05-16 10:41 UTC, okwme commented on docs/polkadot/learn/comparisons/cosmos.md
> +Both the Polkadot relay chain and Cosmos hub will achieve finality under favorable network conditions with the assumption that > 2/3 of the validator set is available and honest. Once > 2/3 of the va
```suggestion
Both the Polkadot relay chain and Cosmos hub will achieve finality under favorable network conditions with the assumption that > 2/3 of the validator set is available and honest. Once > 2/3 of the validator set has signed off on a block (or, in the case of GRANDPA a chain of blocks) those blocks are considered final and unable to be reverted. In comparison, Nakamoto consensus as used in most PoW blockchains can only guarantee probable finality at best.
```

2019-05-16 10:42 UTC, okwme commented on docs/polkadot/learn/comparisons/cosmos.md
> +The time-to-finality of both GRANDPA and Tendermint are limited by the bandwidth limit and latency on the network. As the number of validators increases, so will the number of messages that must get
```suggestion
The time-to-finality of both GRANDPA and Tendermint are limited by the bandwidth limit and latency on the network. As the number of validators increases, so will the number of messages that must get sent between them thereby slowing down the finality mechanism. Both Polkadot and Cosmos are interested in moving to as large of a validator set as possible without horrendously slowing down the network. In practical terms, Cosmos launched with 100 validators and Polkadot will launch with 50 - 100 and quickly scale up to around 1000.
```

2019-05-23 15:02 UTC, keorn requested changes
reviewed up to shared security

2019-05-23 15:02 UTC, keorn commented on docs/polkadot/learn/comparisons/cosmos.md
> +Polkadot and Cosmos share similar goals including interoperability among blockchains, and better security guarantees through use of a Byzantine tolerant finalization mechanism. ...
while cosmos network is focusing a network of connected chains that are individually finalized, Polkadot aims to also enable multiple chains to share the same security infrastructure and enable join finalization

2019-05-23 15:02 UTC, keorn commented on docs/polkadot/learn/comparisons/cosmos.md
> +Polkadot uses a trifecta of the GRANDPA finality gadget, BABE block production, and Nominated Proof-of-Stake (NPoS) validator selection as its consensus framework.
We should better describe what the consensus is over. In Polkadot there is a whole process that leads to assembly of a BABE proposal that involves validity checking. The proposal then includes a number of parachain headers, rather than as in Tendermint only having individual chains having consensus over them.

2019-05-23 15:02 UTC, keorn commented on docs/polkadot/learn/comparisons/cosmos.md
Add a "Liveness" section. One of the main reasons for BABE/GRANDPA split is that BABE is always running and providing confirmations without a large communication overhead as is the case with Tendermint.

2019-05-23 15:02 UTC, keorn commented on docs/polkadot/learn/comparisons/cosmos.md
This section should emphasize how in Polkadot not every validator has to check all state transitions for pooled security. While current proposals from Tendermint make everyone run everyhting.

2019-06-12 09:43 UTC, lsaether commented
@cwgoes @okwme @laboon Ready for review

2019-06-12 12:08 UTC, okwme commented on docs/polkadot/learn/comparisons/cosmos.md
> +Cosmos does not operate under the assumption that all the connected chains have shared state, so in this way each chain is independent and responsible for incentivizing their own security. The Cosmos
```suggestion
Cosmos does not operate under the assumption that all the connected chains have shared state, so in this way each chain is independent and responsible for incentivizing their own security. The Cosmos IBC design does not make additional security guarantees on any of the interchain messaging. If a user decided to send a message from one Cosmos Tendermint chain to another, and later that second chain is corrupted because it had much lower security, it could have an indirect effect on the original chain. Cosmos' model is only as secure as the least secure of the bridged chains that the user uses. It is expected that the security will vary widely between each chain on Cosmos and users of the chains should know and understand this. This is different from Polkadot which is designed to distribute security as a blanket over all parachains through the shared-state model.
```

2019-06-12 12:10 UTC, okwme commented on docs/polkadot/learn/comparisons/cosmos.md
> +Both ICMP and IBC require consensus verification, but ICMP provides state machine verification while IBC leaves this up to aspect up to the user.
```suggestion
Both ICMP and IBC require consensus verification, but ICMP provides state machine verification while IBC leaves this aspect up to the user.
```

2019-06-12 12:13 UTC, okwme commented on docs/polkadot/learn/comparisons/cosmos.md
> +Since the Polkadot relay-chain comes to finality by using the GRANDPA finality gadget, the IBC scheme proposed by Cosmos should be made to work with Polkadot (more on finality in the [section below](
```suggestion
Since the Polkadot relay-chain comes to finality by using the GRANDPA finality gadget, the IBC scheme proposed by Cosmos should be able to work with Polkadot (more on finality in the [section below](#finality)).
```

2019-06-12 12:22 UTC, okwme commented on docs/polkadot/learn/comparisons/cosmos.md
> +Polkadot has stronger liveness than Cosmos' Tendermint.
```suggestion
Polkadot has stronger liveness than Cosmos' Tendermint, which prioritizes safety over liveness.
```

2019-06-12 12:43 UTC, jackzampolin commented on docs/polkadot/learn/comparisons/cosmos.md
> +Cosmos connects to external chains through the use of what are called _peg zones_ which provide a kind of specialized bridge that can understand the external consensus. For all chains that run the "f
```suggestion
Cosmos connects to external chains through the use of what are called _peg zones_ which provide a kind of specialized bridge that can understand the external consensus. For all chains that satisfy [consensus requirements](https://github.com/cosmos/ics/tree/master/spec/ics-002-consensus-verification), their interoperability protocol (known as IBC, more on that below) will work without the need of this special peg.
```

2019-06-12 12:43 UTC, jackzampolin commented on docs/polkadot/learn/comparisons/cosmos.md
> +The Cosmos hub uses a Proof-of-Stake algorithm that weighs validators by the amount of tokens backing them. It also allows smaller holders to delegate their tokens to one of its 100 validators. Howev
```suggestion
The Cosmos hub uses a Proof-of-Stake algorithm that weighs validators by the amount of tokens backing them. It also allows smaller holders to delegate their tokens to one of its validators (currently 100, but there are plans to increase this number to >300). However, other zones in Cosmos may implement variants of this Proof-of-Stake scheme.
```

2019-06-12 12:44 UTC, zmanian approved these changes

2019-06-12 12:47 UTC, jackzampolin commented on docs/polkadot/learn/comparisons/cosmos.md
> +Cosmos does not operate under the assumption that all the connected chains have shared state, so in this way each chain is independent and responsible for incentivizing their own security. The Cosmos
We do have plans to allow hub validators to also validate other chains. Something we are calling interchain collateralization. cc @cwgoes for more info here.

2019-06-12 12:47 UTC, jackzampolin commented on docs/polkadot/learn/comparisons/cosmos.md
> +Polkadot and Cosmos both claim blockchain interoperability.
```suggestion
Polkadot and Cosmos are both working on blockchain interoperability protocols.
```

2019-06-12 12:51 UTC, jackzampolin commented on docs/polkadot/learn/comparisons/cosmos.md
> +Polkadot has stronger liveness than Cosmos' Tendermint, which prioritizes safety over liveness.
```suggestion
Polkadot's design has stronger liveness guarantees than Cosmos' Tendermint, which prioritizes the safety.
```

2019-06-13 17:06 UTC, merged