update staking contents
w3f/polkadot-wiki-old pull request #185
Opened 2019-05-23 14:44 UTC by ansonla3

* How does staking work in Polkadot
* Rewards distribution with an example

2019-05-23 15:38 UTC, laboon requested changes
Minor typos and one question - otherwise looks good!

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +Polkadot uses NPoS (Nominated Proof-of-Stake) as its mechanism for selecting the validator set. It is designed over the roles of **validators** and **nominators**, to maximize chain security. Actors
```suggestion
Polkadot uses NPoS (Nominated Proof-of-Stake) as its mechanism for selecting the validator set. It is designed with the roles of **validators** and **nominators**, to maximize chain security. Actors who are interested in maintaining the network can run a validator node. At genesis, Polkadot will have a limited amount of slots available for these validators, but this number will grow over time to over one thousand. The system also encourages an unlimited number of DOT holders to participate as nominators, where a nominator backs the election of one or more trusted validator candidates, to ensure the network will not be heavily centralized on only a few validators. Validators take the role of both validating blocks and guaranteeing the finality of the chain, while nominators will have the power to choose the set of validators by indicating their support weighted by DOTs. Both validators and nominators will earn rewards proportional to the amount that they stake, with validators having the ability to set some payment preferences.
```

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +Polkadot uses NPoS (Nominated Proof-of-Stake) as its mechanism for selecting the validator set. It is designed over the roles of **validators** and **nominators**, to maximize chain security. Actors
Is this number (over 1,000 validators) verified?  I thought it was still undecided.

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +you can nominate multiple validator candidates that you trust to help you earn rewards. You can take a look at the [nominator guide](http://wiki.polkadot.network/en/latest/polkadot/node/guides/how-to
```suggestion
you can nominate multiple validator candidates that you trust to help you earn rewards in DOTs. You can take a look at the [nominator guide](http://wiki.polkadot.network/en/latest/polkadot/node/guides/how-to-nominate/) to understand what you are required to do when the mainnet launches. Meanwhile, a validator node is required to be responsive 24/7, perform its expected duties in a timely manner, and avoid any slashable behavior. You can follow our [validator guide](http://wiki.polkadot.network/en/latest/polkadot/node/guides/how-to-validate/) if you want to run a validator in the current testnet.
```

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +To estimate the inflation rate and how many DOTs you can get each month as a nominator or validator, you can use this [excel sheet](https://docs.google.com/spreadsheets/d/1-9Hc3kZ23EhZC3X6feRUKSTv6gj
```suggestion
To estimate the inflation rate and how many DOTs you can get each month as a nominator or validator, you can use this [Excel sheet](https://docs.google.com/spreadsheets/d/1-9Hc3kZ23EhZC3X6feRUKSTv6gj4xR7cvUbJD2zUEZk/edit?usp=sharing) as a reference and play around with it by changing some parameters (e.g. validator pools, total supply, commission fees, etc.) to have a better estimate. Even though it may not be entirely accurate since staking participation is changing dynamically, it works well as an indicator.
```

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +### 4. The spirit behind the rewards
This sounds strange to me... how about "Rewards Algorithm Philosophy"?

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +We highlight two features of this payment scheme. The first one is that, since validator pools are paid the same, pools with less stake will pay more to nominators per-DOT than pools with more stake.
```suggestion
We highlight two features of this payment scheme. The first is that since validator pools are paid the same, pools with less stake will pay more to nominators per-DOT than pools with more stake. We thus give nominators an economic incentive to gradually shift their preferences to lower staked validators that gain a sufficient amount of reputation. The reason for this is that we want the stake across validator pools to be as evenly distributed as possible, to avoid a concentration of power among a few validators. In the long term, we expect all validator pools to have similar levels of stake, with the stake being higher for higher reputation validators (meaning that a nominator that is willing to risk more by backing a validator with a low reputation will get paid more, which is reasonable). 
```

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +We also remark that when the network slashes a validator slot for a misbehavior (e.g. validator offline, validating an invalid block, etc.) the slashed amount is a fixed percentage (and NOT a fixed a
```suggestion
We also remark that when the network slashes a validator slot for a misbehavior (e.g. validator offline, validating an invalid block, etc.) the slashed amount is a fixed percentage (and NOT a fixed amount of DOTs), which means that validator pools with more stake get slashed more DOTs. Again, this is done to provide nominators with an economic incentive to shift their preferences and back less popular validators whom they consider to be trustworthy.
```

2019-05-23 15:38 UTC, laboon commented on docs/polkadot/learn/staking.md
> +The second point we want to highlight is that each validator candidate is free to name their desired commission fee (as a percentage of the reward) to cover for operational costs. Since validator poo
```suggestion
The second point we want to highlight is that each validator candidate is free to name their desired commission fee (as a percentage of the reward) to cover operational costs. Since validator pools are paid the same, pools with lower commission fees pay more to nominators than pools with higher fees. Thus, each validator can choose between increasing their fees to earn more DOTs, or decreasing their fees to attract more nominators and increase their chances of being elected. We will let the market regulate itself in this regard. In the long term, we expect that all validators will need to be cost efficient to remain competitive, and that validators with higher reputation will be able to charge slightly higher commission fees (which is fair).
```

2019-05-23 15:43 UTC, ansonla3 commented on docs/polkadot/learn/staking.md
> +Polkadot uses NPoS (Nominated Proof-of-Stake) as its mechanism for selecting the validator set. It is designed over the roles of **validators** and **nominators**, to maximize chain security. Actors
yes, initially it should be small but as time goes on & the network is stable, we eventually would increase the number of validators

2019-05-23 16:02 UTC, ansonla3 commented on docs/polkadot/learn/staking.md
> +### 4. The spirit behind the rewards
um..yeah, how about "Rewards Mechanism"?

2019-05-28 14:29 UTC, laboon approved these changes
Changes look good to me! 👍

2019-05-28 14:29 UTC, laboon commented
I rebased against master so you should be good to merge.

2019-05-28 14:42 UTC, merged