DOT updates
w3f/polkadot-wiki-old pull request #188
Opened 2019-05-24 14:02 UTC by laboon

This updates the DOT and FAQ pages to include the warning about transferring mainnet DOTs and information about DOT sales (text from Jack, with some very minor additions to clarify that this refers to mainnet and not testnet DOTs)

2019-05-24 14:10 UTC, laboon commented
Ready for review @ansonla3 / @lsaether

2019-05-24 14:51 UTC, ansonla3 requested changes

2019-05-24 14:51 UTC, ansonla3 commented on docs/polkadot/learn/DOT.md
> -You can request DOTs from the [faucet](https://faucets.blockxlabs.com/) ask someone to send you DOTs on the [Polkadot Watercooler](https://riot.im/app/#/room/#polkadot-watercooler:matrix.org).
and this one
https://faucet.polkadot.chat/ 
:P

2019-05-24 17:21 UTC, lsaether commented on docs/polkadot/learn/DOT.md
> -You can request DOTs from the [faucet](https://faucets.blockxlabs.com/) ask someone to send you DOTs on the [Polkadot Watercooler](https://riot.im/app/#/room/#polkadot-watercooler:matrix.org).
we will switch to https://faucet.polkadot.network soon too

2019-05-24 17:30 UTC, ansonla3 commented on docs/polkadot/learn/DOT.md
> -You can request DOTs from the [faucet](https://faucets.blockxlabs.com/) ask someone to send you DOTs on the [Polkadot Watercooler](https://riot.im/app/#/room/#polkadot-watercooler:matrix.org).
later on, we can redirect those traffic to that?

2019-05-24 19:33 UTC, laboon commented on docs/polkadot/learn/DOT.md
> -You can request DOTs from the [faucet](https://faucets.blockxlabs.com/) ask someone to send you DOTs on the [Polkadot Watercooler](https://riot.im/app/#/room/#polkadot-watercooler:matrix.org).
I'd say we switch over to  https://faucet.polkadot.network once it's live - until then we can leave it up as .chat.

2019-05-27 05:28 UTC, ansonla3 approved these changes

2019-05-27 05:29 UTC, merged