A bunch of small improvements
w3f/polkadot-wiki-old pull request #204
Opened 2019-06-12 10:30 UTC by lsaether

2019-07-08 18:57 UTC, laboon commented
Logan - sorry, I totally missed this when it came in.  Reviewing now.

2019-07-08 19:02 UTC, laboon commented
Overall looks good with one minor comment in review.

2019-07-08 19:02 UTC, laboon requested changes

2019-07-08 19:02 UTC, laboon commented on docs/polkadot/learn/architecture.md
> +# Architecture
There doesn't seem be a link to the Architecture page on the sidebar.

2019-07-09 09:13 UTC, lsaether commented on docs/polkadot/learn/architecture.md
> +# Architecture
added

2019-07-09 09:14 UTC, laboon approved these changes
👍

2019-07-09 09:16 UTC, merged