Update validator and nominator guides
w3f/polkadot-wiki-old pull request #205
Opened 2019-06-14 09:02 UTC by Tbaut

- update the flow and screenshots to the new account and staking screens

2019-06-14 09:08 UTC, Tbaut commented
I disagree with the spellchecker. I've used grammarly on both guides, although it's not perfect I think most typos got fixed.

2019-06-14 13:21 UTC, lsaether requested changes

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-nominate.md
> +- Select the `controller` as.. the controller. This is the account that will decide when to start or stop nominating.
```suggestion
- Select the `controller`. This is the account that will decide when to start or stop nominating.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-nominate.md
> +- **Stash account** - Select your `stash` account, we will bound 100mili Dots, make sure it has this amount of funds.
```suggestion
- **Stash account** - Select your `stash` account, we will bound 100 milliDOTs, make sure it has this amount of funds.
```

We need to standardize how we write the DOT units, I prefer attaching the prefix without a hyphen like so "milli-DOT."

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-nominate.md
> +Once you've created your accounts you will need to acquire some DOTs. See the [DOTs page](../../learn/DOT.md#getting-testnet-dots) for recommendations on getting testnet DOTs. Each of your accounts s
```suggestion
Once you've created your accounts you will need to acquire some DOTs. See the [DOTs page](../../learn/DOT.md#getting-testnet-dots) for recommendations on getting testnet DOTs. Each of your accounts should have at least 150 milliDOTs to cover the existential deposit and transaction fees.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-nominate.md
> +Go back to the *Account Actions* tab and click the `Nominate` button. Fill in the blank field with the address of the validators you have chosen to nominate. After signing and submitting your transac
```suggestion
Go back to the *Account Actions* tab and click the `Nominate` button. Fill in the blank field with the address of the validators you have chosen to nominate. After signing and submitting your transaction you should see the button `Stop Nominating` and you should see the accounts you are nominating showing up under the `Nominating` section. Your nomination will be effective in the next era (this can take up to one hour).
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +To help you identify your accounts easily later on, make sure to use `stash`, `controller` and `session` in the name your accounts. A mnemonic seed phrase is given to you. You can save it in a safe p
```suggestion
To help you identify your accounts easily later on, make sure to use `stash`, `controller` and `session` in the name your accounts. A mnemonic seed phrase is given to you. You can save it in a safe place, offline, or you can choose to save your account using a JSON keyfile that will be generated automatically when clicking on `Save`. The password that is required to create an account will be used to sign any transaction made for each account. It will also be used to encrypt the JSON keyfile and will be required if you wish to restore your account using this file.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +Another particularity you need to be aware of: both `stash` and `controller` account can use the `Schnorrkel (sr25519)` as keypair crypto type in the `Advanced creation options`, however, you must us
```suggestion
Another particularity you need to be aware of: both `stash` and `controller` account can use the `Schnorrkel (sr25519)` as keypair crypto type in the `Advanced creation options`, however, **you must use `Edwards (ed25519)` for the session account.**
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +To continue the following steps, you are required to get some testnet DOTs token for the `stash` and `controller` accounts in order to submit transactions and use these DOTs as stake. The `session` a
```suggestion
To continue the following steps, you are required to get some testnet DOTs token for the `stash` and `controller` accounts in order to submit transactions and use these DOTs as stake. The `session` account doesn't need any DOT. See the [DOTs page](../../learn/DOT.md#getting-testnet-dots) for recommendations on getting testnet DOTs. Each of your accounts should have at least 150 milliDOTs to cover the existential deposit and transaction fees.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +- Select the `controller` as.. the controller. This is the account that will decide when to start or stop validating.
```suggestion
- Select the `controller`. This is the account that will decide when to start or stop validating.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +- Select the `session` account as.. the session. This is the account whose seed will be used to run the node.
```suggestion
- Select the `session` account. This is the account whose seed will be used to run the node.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +- **Stash account** - Select your `stash` account, we will bound 100mili Dots, make sure it has this amount of funds.
```suggestion
- **Stash account** - Select your `stash` account, we will bound 100 milliDOTs, make sure it has this amount of funds.
```

2019-06-14 13:21 UTC, lsaether commented on docs/polkadot/node/guides/how-to-validate.md
> +polkadot --validator --key="SESSION_ACCOUNT_SEED" --name NAME_ON_TELEMETRY
```suggestion
polkadot --chain alex --validator --key="SESSION_ACCOUNT_SEED" --name NAME_ON_TELEMETRY
```

2019-06-14 15:31 UTC, Tbaut commented
Thanks for the review. I have no objection :)

2019-06-16 13:11 UTC, lsaether approved these changes

2019-06-16 13:11 UTC, merged