staking chinese
w3f/polkadot-wiki-old pull request #213
Opened 2019-07-01 10:18 UTC by ansonla3

2019-07-08 18:56 UTC, laboon commented
Anson - who do you think could review this?  I don't know who on our team would be able to besides you.

2019-07-09 08:57 UTC, lsaether commented
@laboon We have a couple volunteers from the community who help out with Chinese reviews. I believe Anson is able to ask them when it's ready?

2019-07-10 02:16 UTC, Satoshi-Kusumoto requested changes
LGTM with a few minor issues
Other modifications try to improve consistency across the context.

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +波卡链（Polkadot）使用 NPoS（提名权益证明）机制选择验证人集合，该机制创建了**验证人**和**提名人**两种角色，以实现链安全性的最大化。对网络维护感兴趣的参与者可以负责运行验证人节点。在创世区块中，波卡链将为验证人提供有限位置，位置数量将逐步增加至 1000 以上。同时，此系统还鼓励大量 DOT 持有人成为提名人参与其中。提名人将参与选举出一个或多个可信赖的验证人候选人，以确保网
```suggestion
波卡链（Polkadot）使用 NPoS（提名权益证明）机制选择验证人集合，该机制创建了**验证人**和**提名人**两种角色，以实现链安全性的最大化。对网络维护感兴趣的参与者可以负责运行验证人节点。在创世区块中，波卡链将为验证人提供有限位置，位置数量将逐步增加至 1000 以上。同时，系统还鼓励任何 DOT 持有人成为提名人参与其中。提名人将参与选举出一个或多个可信赖的验证人候选人，以确保网络不会因仅有的少数几名验证人而过于中心化。验证人将同时负责验证区块和确保最终确定性(finality)，而提名人则有权通过 DOT 表明支持对象并选择多个验证人。验证人和提名人都将获得与各自权益成比例的奖励，同时验证人还可对分成方式进行设置。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +在抵押中，你可以充当提名人或验证人。提名人可提名多名可信赖的验证候选人，来帮助你获得 DOT 奖励。你可以看一下[提名人指南](../../../polkadot/node/guides/how-to-nominate.md)使帮助你了解在主网启动时需进行哪些操作。而验证人节点则需24/7全天候运行，以便及时执行预定任务并避免任何引发削减的行为。如你想在当前测试网中充当验证人角色，可查阅[验证人
```suggestion
在抵押中，你可以充当提名人或验证人。提名人可提名多名可信赖的验证候选人，来帮助你获得 DOT 奖励。你可以看一下[提名人指南](../../../polkadot/node/guides/how-to-nominate.md)从而帮助你了解在主网启动时需进行哪些操作。而验证人节点则需24/7全天候运行，以便及时执行预定任务并避免任何引发Slash惩罚的行为。如你想在当前测试网中充当验证人角色，可查阅[验证人指南](../node/guides/how-to-validate.md)。
```
There is no word in Chinese that has the same meaning as 'slash' or 'slashing'. When talking about them in Chinese, we just use the English word 'slash'

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +所有潜在验证人都可表明其希望成为验证人候选人的意愿。他们的候选资格将向所有提名人公开，提名人将依次提交所支持的候选人名单。在接下来的纪元(era)（持续几个小时）中，拥有最多 DOT 支持的验证人将被选出被成为验证人。这里没有对 DOT 持有人成为提名人提出特别要求，但我们希望每位提名人都能仔细跟踪验证人的表现和声誉。
```suggestion
所有潜在验证人都可表明其希望成为验证人候选人的意愿。他们的候选资格将向所有提名人公开，提名人将依次提交所支持的候选人名单。在接下来的纪元(epoch)（持续几个小时）中，拥有最多 DOT 支持的验证人将被选为验证人。这里没有对 DOT 持有人成为提名人提出特别要求，但我们希望每位提名人都能仔细跟踪验证人的表现和声誉。
```
The original text uses 'epoch' instead of 'era'

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +提名期结束后，NPoS 选举机制将输入提名人及其投票，并输出一组符合要求的验证人。该规模能够使验证人获得最大化的权益支持，并尽可能使支持验证人的权益呈均匀分布。此选举机制旨在提高网络安全性，确保提名人的公平代表性。如你想进一步了解更多 NPoS 的工作原理（例如选举、运行时间复杂度等），请点击[此处](http://research.web3.foundation/en/latest/polka
```suggestion
提名期结束后，NPoS 选举机制将输入提名人及其投票，并输出一组符合要求的验证人，其中每个验证人都能获得最大化的权益支持，并且支持验证人的权益会尽可能呈均匀分布。此选举机制旨在提高网络安全性，确保提名人的公平代表性。如你想进一步了解更多 NPoS 的工作原理（例如选举、运行时间复杂度等），请点击[此处](http://research.web3.foundation/en/latest/polkadot/NPoS/)阅读。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +在了解验证人和提名人的奖励制度前，我们需要对**验证人池**进行了解。验证人池由一名当选的验证人和数位支持他的提名人组成。（注意：如果提名人 n 并支持多位当选验证人，比如 k 位，NPoS 选举机制将会把 n 的权益分成 s_1、s_2、…、s_k，使支持验证人 i 时权益是 s_i。在这种情况下，假若不同池中有 k 名提名人，那么提名人 n 获得的奖励将相同。各提名人支持验证人 i 的权益均
```suggestion
在了解验证人和提名人的奖励制度前，我们需要对**验证人池**进行了解。验证人池由一名当选的验证人和数位支持他的提名人组成。（注意：如果提名人 n 支持多位当选验证人，比如 k 位，NPoS 选举机制将会把 n 的权益分成 s_1、s_2、…、s_k，使支持验证人 i 时权益是 s_i。这种情况下提名人 n 获得的奖励，和假设不同池中有 k 名提名人，各提名人支持验证人 i 的权益均为 s_i 的情况下获得的奖励相同）。在各验证人池中都有一份权益关系的提名人列表。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +同时还需注意，验证人若出现错误行为（例如验证人离线、验证区块无效等），网络将削减其插槽数量，削减值为固定的百分比（而非固定的 DOT 值）。这意味着权益更多的验证人池将被削减更多的 DOT。同样地，这也是为了给提名人提供一种经济激励，使其改变偏好去支持那些他们认为值得信任却不受欢迎的验证人。
```suggestion
同时还需注意，验证人若出现不良行为（例如验证人离线、验证区块无效等），网络将对其按固定的百分比（而非固定的 DOT 值）做出Slash惩罚。这意味着权益更多的验证人池将损失更多的 DOT。同样地，这也是为了给提名人提供一种经济激励，使其改变偏好去支持那些他们认为值得信任却不那么受欢迎的验证人。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +第二个特点是，各验证人候选人均可自由設定佣金(以奖励百分比的形式）以弥补运行成本。由于各验证人池的奖励相同，因此佣金较低的池向提名人分成的奖励要多于高于佣金较高的池。因此，所有验证人均可自由选择是提高佣金获得更多 DOTs，还是降低佣金吸引更多提名人、增加当选的机会。在这一方面，我们允许市场自我调节。从长期来看，我们希望所有验证人都具有成本效益以维持其竞争力，同时声誉好的验证人可以收取略高的佣金
```suggestion
第二个特点是，各验证人候选人均可自由设定佣金(以奖励百分比的形式）以弥补运行成本。由于各验证人池的奖励相同，因此佣金较低的池向提名人分成的奖励要多于高于佣金较高的池。因此，所有验证人均可自由选择是提高佣金获得更多 DOT，还是降低佣金吸引更多提名人、增加当选的机会。在这一方面，我们允许市场自我调节。从长期来看，我们希望所有验证人都具有成本效益以维持其竞争力，同时声誉好的验证人可以收取略高的佣金（这一点十分公平）。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +由于验证人位置有限，因此大多数意欲抵押 DOT 并提升网络经济安全的参与者将扮演提名人的角色。验证人需负责大部分繁重工作，它們在 BABE 中生成新区块、在 GRANDPA 中进行投票并达成共识、验证平行链的 STF，以及其他一些与数据可用性相关的职责。而作为提名人，在绑定 DOT 后便无需进行任何操作。提名人的任务类似于“设置并忘记”，而验证人则需执行关键操作为本网络提供切实服务。鉴于此，验证
```suggestion
由于验证人位置有限，因此大多数意欲抵押 DOT 并提升网络经济安全的参与者将扮演提名人的角色。验证人需负责大部分繁重工作，它們在 BABE 中生成新区块、在 GRANDPA 中进行投票并达成共识、验证平行链的 STF，以及其他一些与数据可用性相关的职责。而作为提名人，在绑定 DOT 后便无需进行任何操作。提名人的任务类似于“设置并忘记”，而验证人则需执行关键操作为本网络提供切实服务。鉴于此，验证人在获取Staking收益方面拥有部分特权，并且在将相关奖励发放至各提名人之前就可以抽取佣金。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +## 削减
```suggestion
## Slash惩罚
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +当验证人被报告离线多次时，系统将进行削减操作。是否削减本质上取决于两个参数，即`Offline Slash Grace`和`Unstake Threshold`。`Offline Slash Grace`由本网络进行配置，当前测试网配置设为 `4`，而`Unstake Threshold`则由验证人决定。不过在当前设置中，`Unstake threshold`的最大值不得超过 10。
```suggestion
当验证人被报告离线多次时，系统将进行Slash惩罚操作。是否惩罚本质上取决于两个参数，即`Offline Slash Grace`和`Unstake Threshold`。`Offline Slash Grace`由本网络进行配置，当前测试网配置设为 `4`，而`Unstake Threshold`则由验证人决定。不过在当前设置中，`Unstake threshold`的最大值不得超过 10。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +简言之，当验证人被报告离线的次数超过 `Offline Slash Grace + Unstake threshold` 次数，将触发削减。
```suggestion
简言之，当验证人被报告离线的次数超过 `Offline Slash Grace + Unstake threshold` 次数，将触发Slash惩罚。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +此外，削减一旦确定，系统将从验证人的余额以及所有投票给该验证人的提名人的余额中扣除相关数值。
```suggestion
此外，Slash惩罚一旦确定，系统将从验证人的余额以及所有投票给该验证人的提名人的余额中扣除相应DOT。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +    在这种情况下，只有当验证人被报告离线超过 9 次时削减才会发生。
```suggestion
    在这种情况下，只有当验证人被报告离线超过 9 次时Slash才会发生。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +基于Alexander 测试网络的当前配置，奖励将按大约 5 分钟的会话进行记录，并按纪元(era)进行支付。一个纪元为 1 个小时；这意味着奖励将按小时分配给验证人和提名人。
```suggestion
基于Alexander 测试网络的当前配置，奖励将按大约 5 分钟的会话(session)进行记录，并按纪元(era)进行支付。一个纪元为 1 个小时；这意味着奖励将按小时分配给验证人和提名人。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +验证人可以创建不与提名人共享的部分奖励。在扣除相关金额后，剩余部分将以抵押值为基础，分配至验证人和所有投票给该验证人的提名人。
```suggestion
验证人可以创建不与提名人共享的部分奖励(佣金)。在扣除相关金额后，剩余部分将以抵押值为基础，分配至验证人和所有投票给该验证人的提名人。
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +例如:假设奖励为 100 DOTs
```suggestion
例如:假设奖励为 100 DOT
```

2019-07-10 02:16 UTC, Satoshi-Kusumoto commented on docs/lang/chinese/learn/staking.md
> +验证人可以指定 `validator_payment（验证人报酬） = 50 DOTs`，剩余 50 DOTs 将根据各自所持有的权益比例分配给验证人和提名人。
```suggestion
验证人可以指定 `validator_payment（佣金） = 50 DOT`，剩余 50 DOT 将根据各自所持有的权益比例分配给验证人和提名人。
```

2019-07-10 02:21 UTC, Satoshi-Kusumoto commented
@lsaether  Hi, I am the John who contacted you on email. 
I talked with Anson and took the review work.

2019-07-10 08:23 UTC, ansonla3 commented on docs/lang/chinese/learn/staking.md
> +在抵押中，你可以充当提名人或验证人。提名人可提名多名可信赖的验证候选人，来帮助你获得 DOT 奖励。你可以看一下[提名人指南](../../../polkadot/node/guides/how-to-nominate.md)使帮助你了解在主网启动时需进行哪些操作。而验证人节点则需24/7全天候运行，以便及时执行预定任务并避免任何引发削减的行为。如你想在当前测试网中充当验证人角色，可查阅[验证人
I think we can still keep 削减 but with (Slash) next to that

2019-07-10 08:42 UTC, Satoshi-Kusumoto approved these changes

2019-07-10 08:45 UTC, merged