Add page on validator payout mechanism (fixes #234)
w3f/polkadot-wiki-old pull request #235
Opened 2019-08-09 01:52 UTC by laboon

Fixes #234 

This adds a page with a brief description and some examples of how the validator payout mechanism works and some examples showing why it is encouraged (and beneficial) to run multiple validators.

2019-08-09 01:54 UTC, laboon commented
@lsaether @jplatts12 Can you review?

2019-08-09 01:56 UTC, laboon commented
Not sure why circleCI can't even hit the main page.  Did something change recently with the setup?  I'm rebased against latest master.

2019-08-09 04:43 UTC, ansonla3 submitted a review, later dismissed
oops, I pressed the wrong button

2019-08-09 07:37 UTC, lsaether requested changes
A couple wording nits. Otherwise clear and concise article.

I would also suggest to include some information on validator preferences. Validators can choose to take a cut out of the rewards before distributing the payment to nominators and self stake. This is another incentive for a single entity to run more than one validator but does not get mentioned here.

2019-08-09 07:37 UTC, lsaether commented on docs/polkadot/node/guides/validator-payout.md
> +The initial goal of the Kusama network is to have 50 - 100 validators after the initial proof-of-authority phase.  Not all of these validators must be run by different entities (companies or people);
```suggestion
The initial goal of the Kusama network is to have 50 - 100 validators after the initial proof-of-authority phase.  Not all of these validators must be run by different entities (companies or people); in fact, it may be to your advantage to run multiple validators.
```

I would avoid making a judgement on this until we see what goes down in the wild.

2019-08-09 07:37 UTC, lsaether commented on docs/polkadot/node/guides/validator-payout.md
> +It is possible for a single entity to run multiple validators.  It is explicitly encouraged by the protocol, as some examples will show.  Assuming you have enough DOTs, or enough stake nominates your
```suggestion
It is possible for a single entity to run multiple validators.  Examples will show that it sometimes makes good business sense to do so.  Assuming you have enough DOTs, or enough stake nominates your validator, to ensure that your validators remain in the validator set, running multiple validators will often result in a higher return than running a single validator.
```

I push back a bit on the idea that the protocol explicitly encourages single entities to run multiple validators. It encourages a validator set not controlled by massive token holders, ideally a more decentralized validator set. IMO encouraging a single entity to run more than one validator doesn't seem sustainable long term, although I acknowledge it sometimes makes good business sense. 

Devil's Advocate: Why doesn't a large stakeholder simply nominate their tokens to other validators? It would be less costs on them and easier management.

2019-08-09 07:39 UTC, lsaether commented
Sometimes CI breaks for no good reason. When this happen you can usually fix it by restarting the job once or twice.

2019-08-09 09:15 UTC, jplatts12 commented on docs/polkadot/node/guides/validator-payout.md
> +It is possible for a single entity to run multiple validators.  It is explicitly encouraged by the protocol, as some examples will show.  Assuming you have enough DOTs, or enough stake nominates your
Then they do not get the commissions, so they will make materially less rewards while also entrusting someone else with their tokens. If you have a validator set-up then spinning up another instance is a marginal cost.

2019-08-09 13:53 UTC, laboon commented on docs/polkadot/node/guides/validator-payout.md
> +The initial goal of the Kusama network is to have 50 - 100 validators after the initial proof-of-authority phase.  Not all of these validators must be run by different entities (companies or people);
Yeah, this was part of the original rationale for the issue but you're right, I don't think it needs to be made explicit and Jack is fine with removing it as well.

2019-08-09 13:56 UTC, laboon commented
> I would also suggest to include some information on validator preferences. Validators can choose to take a cut out of the rewards before distributing the payment to nominators and self stake. This is another incentive for a single entity to run more than one validator but does not get mentioned here.

Yes, I was trying to keep this as simple as possible (since all of this information _is_ already available on the wiki, it's just spread around a bit).  I'll detail it, although I'll limit to a paragraph and explain that for simplicity's sake, I am assuming no validator cut in the payout examples.

2019-08-09 14:00 UTC, laboon commented on docs/polkadot/node/guides/validator-payout.md
> +It is possible for a single entity to run multiple validators.  It is explicitly encouraged by the protocol, as some examples will show.  Assuming you have enough DOTs, or enough stake nominates your
From a game-theoretical perspective, large stakeholders (large enough where splitting their stake to multiple validators allows all of the "baby validators" to remain in the validator set)  _are_ explicitly encouraged since it will mean increasing their share of the payout.  It also biases the system toward relatively equal stake between validators, as you want to stake just enough to ensure that your validator(s) stay(s) in the validator set.

2019-08-09 14:02 UTC, laboon commented on docs/polkadot/node/guides/validator-payout.md
> +It is possible for a single entity to run multiple validators.  It is explicitly encouraged by the protocol, as some examples will show.  Assuming you have enough DOTs, or enough stake nominates your
I'd be happy to say something like "are encouraged under certain circumstances" because I guess it's not actually "explicit" _per se_.

2019-08-09 15:23 UTC, laboon commented on docs/polkadot/node/guides/validator-payout.md
> +It is possible for a single entity to run multiple validators.  It is explicitly encouraged by the protocol, as some examples will show.  Assuming you have enough DOTs, or enough stake nominates your
Reworded to explain the benefits without actually saying that it is explicitly encouraged

2019-08-09 15:24 UTC, laboon commented
This turned out to be more than just a few paragraphs as originally asked for! =)

I added a section at the bottom on nominating vs validating and how it impacts rewards.  I tried putting it earlier but I couldn't find a good place to make it flow.

I also added it to mkdocs.yml so that it is visible without going through the validator overview page.

@lsaether Can you take another look please?

2019-08-09 15:25 UTC, laboon commented on docs/polkadot/node/guides/validator-payout.md
> +The initial goal of the Kusama network is to have 50 - 100 validators after the initial proof-of-authority phase.  Not all of these validators must be run by different entities (companies or people);
Removed

2019-08-10 06:06 UTC, lsaether approved these changes

2019-08-10 14:37 UTC, laboon commented
👍

2019-08-10 14:37 UTC, merged

2019-08-10 14:38 UTC, laboon commented
CC @jplatts12 , this is merged now, should be up on site soon