Adds treasury information
w3f/polkadot-wiki-old pull request #251
Opened 2019-08-27 15:12 UTC by lsaether

closes #173

2019-08-27 20:51 UTC, laboon requested changes
Overall looks good, some minor grammar tweaks

2019-08-27 20:51 UTC, laboon commented on docs/polkadot/learn/treasury.md
> +spent.
Minor point, but there are some superfluous carriage returns in here.  

Actually reviewing this I don't think it's a big deal, as they aren't displayed.  It might even make reviewing easier since there aren't such huge lines to find the diffs in.

2019-08-27 20:51 UTC, laboon commented on docs/polkadot/learn/treasury.md
> +Proposals may consist of (but not limited to):
```suggestion
Proposals may consist of (but are not limited to):
```

2019-08-27 20:51 UTC, laboon commented on docs/polkadot/learn/treasury.md
> +The treasury is ultimately controlled by the stakeholders and it will be up to their judgment for how the funds will be
```suggestion
The treasury is ultimately controlled by the stakeholders, and how the funds will be spent is up to their judgment. 
```

2019-08-27 20:51 UTC, laboon commented on docs/polkadot/learn/treasury.md
> +spent.
```suggestion
```

2019-08-27 21:19 UTC, lsaether commented on docs/polkadot/learn/treasury.md
> +spent.
Haha, it's since I put the ruler on my editor for 100 chars, I now try to carriage return so it displays nicely there. Unfortunately it looks like GitHub editor may have a width that doesn't display it as nicely as my editor does...

2019-08-27 22:03 UTC, ansonla3 commented
LGTM

2019-08-28 09:46 UTC, ansonla3 approved these changes

2019-08-28 14:04 UTC, laboon approved these changes

2019-08-28 14:52 UTC, merged