Secure validator guide
w3f/polkadot-wiki-old pull request #268
Opened 2019-09-08 19:21 UTC by ansonla3

2019-09-11 22:49 UTC, lsaether requested changes
Just went through with a high-level check and made some suggestions for fluency. I'm fine with merging this after these suggestions are addressed.

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +This article is based on the [polkadot-secure-validator](https://github.com/w3f/polkadot-secure-validator) repository to write and assumes you have already set up a Polkadot / Kusama validator. If no
```suggestion
The following article is based on the [polkadot-secure-validator](https://github.com/w3f/polkadot-secure-validator) repository and assumes you have already set up a Polkadot or Kusama validator. If do not have any validator set-up experience, please follow the guide [here](https://guide.kusama.network/en/latest/try/validate/) for an introductory tutorial first.
```

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +In this guide, we will enhance the security of the validator by setting up public nodes, as well as configure a VPN to make your validator communicate only with the public nodes.
```suggestion
In this guide, we will enhance the security of the validator by setting a layered architecture with public nodes and a private validator node. The validator is configured on a VPN with the public nodes so that it's only visible to its own public nodes for communication.
```

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +- Configured the firewall
```suggestion
- Configured the firewall.
```

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +- Set up and configured the Wireguard
```suggestion
- Set up and configured the Wireguard.
```

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +- Ran a validator with public node
```suggestion
- Ran a validator with public nodes.
```

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +If you have experience with devops tools such as `Terraform` and `Ansible`, please check out the [secure validator setup](https://github.com/w3f/polkadot-secure-validator) repository. This tool does
```suggestion
If you have experience with devops tools such as `Terraform` and `Ansible`, please check out the [secure validator setup](https://github.com/w3f/polkadot-secure-validator) repository. This tool does everything we talked about above, but you still need to define some credentials (e.g. IP of your server) in the inventory file and then you can manage the relevant servers in an automated way. 
```

2019-09-11 22:49 UTC, lsaether commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +## Todos
Let's remove these Todos before we merge.

2019-09-12 08:29 UTC, fgimenez requested changes
Looks good! ::)

2019-09-12 08:29 UTC, fgimenez commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +ufw allow 30333/tcp
The p2p port is only required on public nodes, it should be closed on the validator.

2019-09-12 08:29 UTC, fgimenez commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +polkadot --name "Public Node A"
You should also add `--no-telemetry` here, by default the network state is sent to telemetry, and for public nodes it includes the IP of the validator.

2019-09-12 09:23 UTC, lsaether approved these changes

2019-09-12 13:54 UTC, fgimenez requested changes

2019-09-12 13:54 UTC, fgimenez commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +# wireguard port  (Note: Only validator is required)
Nope :) the VPN port must be open in both validator and public nodes.

2019-09-12 13:54 UTC, fgimenez commented on docs/polkadot/node/guides/how-to-set-up-secure-validate.md
> +
Here is missing the `--no-telemetry` flag, although it is used later in the command. `--no-telemetry` should be used in both the validator and the public nodes.

2019-09-12 14:00 UTC, fgimenez approved these changes
Cool thx!

2019-09-12 14:04 UTC, merged